
apiVersion: v1
kind: ResourceQuota
metadata:
  name: qoves-app-quota
  namespace: qoves-app
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "6"
    limits.memory: 4Gi
    pods: "20"
    persistentvolumeclaims: "2"
    requests.storage: 5Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: qoves-app-defaults
  namespace: qoves-app
spec:
  limits:
    - type: Container
      default:
        cpu: 200m
        memory: 256Mi
      defaultRequest:
        cpu: 50m
        memory: 64Mi
      max:
        cpu: "1"
        memory: 1Gi
