
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: qoves-app

automountServiceAccountToken: false
---
apiVersion: external-secrets.io/v1beta1

kind: SecretStore
metadata:
  name: vault
  namespace: qoves-app
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      
      path: qoves
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          
          role: qoves-app
          serviceAccountRef:
            name: vault-auth
