apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qoves-app
resources:
  - service.yaml
  - deployment.yaml
  - ingress.yaml
  - hpa.yaml
  
images:
  - name: qoves-api
    newName: qoves-api
    newTag: 0.1.0
